name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 📦 Build
        run: pnpm build

      - name: 📦 Lint
        run: pnpm lint

      - name: 📦 Test types
        run: pnpm test:types

      - name: 🧪 Test & coverage
        run: pnpm run test:coverage

      - name: 🟩 Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
